export default {
  Men: [
    'T-Shirts',
    'Polo Shirts',
    'Hoodies',
    'Sweatshirts',
    'Tank Tops',
    'Long Sleeve Tees',
    'Shorts',
    'Pants',
    'Jeans',
    'Jackets',
    'Blazers',
  ],
  Women: [
    'T-Shirts',
    'Blouses',
    'Tank Tops',
    'Crop Tops',
    'Hoodies',
    'Sweatshirts',
    'Dresses',
    'Skirts',
    'Shorts',
    'Pants',
    'Jeans',
    'Jackets',
    'Blazers',
  ],
  Unisex: [
    'T-Shirts',
    'Hoodies',
    'Sweatshirts',
    'Tank Tops',
    'Long Sleeve Tees',
    'Shorts',
    'Pants',
    'Jackets',
  ],
  Boy: [
    'T-Shirts',
    'Tank Tops',
    'Hoodies',
    'Sweatshirts',
    'Shorts',
    'Pants',
    'Jeans',
    'Jackets',
  ],
  Girl: [
    'T-Shirts',
    'Tank Tops',
    'Hoodies',
    'Sweatshirts',
    'Shorts',
    'Pants',
    'Jeans',
    'Dresses',
    'Skirts',
    'Rompers',
    'Jackets',
  ],
  Baby: ['Onesies', 'Bodysuits', 'Rompers', 'Sleepers', 'T-Shirts', 'Pants'],
};
