export default {
  'T-Shirts': [
    '100% Cotton',
    'Cotton Blend',
    'Organic Cotton',
    'Bamboo',
    'Modal',
    'Polyester',
    'Cotton-Polyester Blend',
  ],
  'Polo Shirts': [
    '100% Cotton Pique',
    'Cotton Blend Pique',
    'Performance Cotton',
    'Moisture-Wicking Fabric',
  ],
  Hoodies: ['Fleece', 'French Terry', 'Cotton Blend', 'Organic Cotton', 'Recycled Polyester'],
  Sweatshirts: ['French Terry', 'Fleece', 'Cotton Blend', 'Organic Cotton'],
  'Tank Tops': ['100% Cotton Jersey', 'Cotton Blend', 'Moisture-Wicking', 'Performance Fabric'],
  'Long Sleeve Tees': [
    '100% Cotton Jersey',
    'Cotton Blend',
    'Organic Cotton',
    'Performance Fabric',
  ],
  Shorts: ['Cotton Twill', 'Cotton Blend', 'Performance Fabric', 'Denim'],
  Pants: ['Cotton Twill', 'Cotton Blend', 'Performance Fabric', 'Stretch Cotton'],
  Jeans: ['100% Cotton Denim', 'Stretch Denim', 'Organic Cotton Denim', 'Recycled Denim'],
  Jackets: ['Cotton Canvas', 'Cotton Blend', 'Performance Fabric', 'Waterproof Material'],
  Blazers: ['Wool Blend', 'Cotton Blend', 'Performance Fabric', 'Stretch Fabric'],
  Blouses: ['Cotton Poplin', 'Cotton Blend', 'Silk', 'Polyester'],
  'Crop Tops': ['Cotton Jersey', 'Cotton Blend', 'Performance Fabric'],
  Dresses: ['Cotton Poplin', 'Cotton Blend', 'Jersey', 'Chiffon'],
  Skirts: ['Cotton Twill', 'Cotton Blend', 'Denim', 'Performance Fabric'],
  Rompers: ['Cotton Jersey', 'Cotton Blend', 'Organic Cotton'],
  Onesies: ['Cotton Jersey', 'Organic Cotton', 'Cotton Blend'],
  Bodysuits: ['Cotton Jersey', 'Organic Cotton', 'Cotton Blend'],
  Sleepers: ['Cotton Jersey', 'Organic Cotton', 'Cotton Blend'],
};
