export default {
  Men: {
    'T-Shirts': ['Chest', 'Length', 'Sleeve'],
    'Polo Shirts': ['Chest', 'Length', 'Sleeve'],
    Hoodies: ['Chest', 'Length', 'Sleeve'],
    Sweatshirts: ['Chest', 'Length', 'Sleeve'],
    'Tank Tops': ['Chest', 'Length'],
    'Long Sleeve Tees': ['Chest', 'Length', 'Sleeve'],
    Shorts: ['Waist', 'Length', 'Thigh'],
    Pants: ['Waist', 'Length', 'Thigh'],
    Jeans: ['Waist', 'Length', 'Thigh'],
    Jackets: ['Chest', 'Length', 'Sleeve'],
    Blazers: ['Chest', 'Length', 'Sleeve'],
  },
  Women: {
    'T-Shirts': ['Bust', 'Length', 'Sleeve'],
    Blouses: ['Bust', 'Length', 'Sleeve'],
    'Tank Tops': ['Bust', 'Length'],
    'Crop Tops': ['Bust', 'Length'],
    Hoodies: ['Bust', 'Length', 'Sleeve'],
    Sweatshirts: ['Bust', 'Length', 'Sleeve'],
    Dresses: ['Bust', 'Waist', 'Length'],
    Skirts: ['Waist', 'Length', 'Hip'],
    Shorts: ['Waist', 'Length', 'Thigh'],
    Pants: ['Waist', 'Length', 'Thigh'],
    Jeans: ['Waist', 'Length', 'Thigh'],
    Jackets: ['Bust', 'Length', 'Sleeve'],
    Blazers: ['Bust', 'Length', 'Sleeve'],
  },
  Unisex: {
    'T-Shirts': ['Chest', 'Length', 'Sleeve'],
    Hoodies: ['Chest', 'Length', 'Sleeve'],
    Sweatshirts: ['Chest', 'Length', 'Sleeve'],
    'Tank Tops': ['Chest', 'Length'],
    'Long Sleeve Tees': ['Chest', 'Length', 'Sleeve'],
    Shorts: ['Waist', 'Length', 'Thigh'],
    Pants: ['Waist', 'Length', 'Thigh'],
    Jackets: ['Chest', 'Length', 'Sleeve'],
  },
  Boy: {
    'T-Shirts': ['Chest', 'Length', 'Sleeve'],
    'Tank Tops': ['Chest', 'Length'],
    Hoodies: ['Chest', 'Length', 'Sleeve'],
    Sweatshirts: ['Chest', 'Length', 'Sleeve'],
    Shorts: ['Waist', 'Length', 'Thigh'],
    Pants: ['Waist', 'Length', 'Thigh'],
    Jeans: ['Waist', 'Length', 'Thigh'],
    Jackets: ['Chest', 'Length', 'Sleeve'],
  },
  Girl: {
    'T-Shirts': ['Chest', 'Length', 'Sleeve'],
    'Tank Tops': ['Chest', 'Length'],
    Hoodies: ['Chest', 'Length', 'Sleeve'],
    Sweatshirts: ['Chest', 'Length', 'Sleeve'],
    Shorts: ['Waist', 'Length', 'Thigh'],
    Pants: ['Waist', 'Length', 'Thigh'],
    Jeans: ['Waist', 'Length', 'Thigh'],
    Dresses: ['Bust', 'Length'],
    Skirts: ['Waist', 'Length', 'Hip'],
    Rompers: ['Chest', 'Length'],
    Jackets: ['Chest', 'Length', 'Sleeve'],
  },
  Baby: {
    Onesies: ['Chest', 'Length'],
    Bodysuits: ['Chest', 'Length'],
    Rompers: ['Chest', 'Length'],
    Sleepers: ['Chest', 'Length'],
    'T-Shirts': ['Chest', 'Length'],
    Pants: ['Waist', 'Length'],
  },
};
