export default {
  'T-Shirts': ['Single needle hem', 'Coverstitch shoulder', 'Overlock seams', 'Flatlock seams'],
  'Polo Shirts': [
    'Single needle hem',
    'Coverstitch shoulder',
    'Overlock seams',
    'Flatlock seams',
    'Buttonhole stitching',
  ],
  Hoodies: [
    'Single needle hem',
    'Coverstitch shoulder',
    'Overlock seams',
    'Flatlock seams',
    'Double needle hem',
  ],
  Sweatshirts: ['Single needle hem', 'Coverstitch shoulder', 'Overlock seams', 'Flatlock seams'],
  'Tank Tops': ['Single needle hem', 'Coverstitch shoulder', 'Overlock seams', 'Flatlock seams'],
  'Long Sleeve Tees': [
    'Single needle hem',
    'Coverstitch shoulder',
    'Overlock seams',
    'Flatlock seams',
  ],
  Shorts: ['Single needle hem', 'Overlock seams', 'Flatlock seams', 'Double needle hem'],
  Pants: ['Single needle hem', 'Overlock seams', 'Flatlock seams', 'Double needle hem'],
  Jeans: ['Chain stitch', 'Overlock seams', 'Flatlock seams', 'Double needle hem'],
  Jackets: ['Single needle hem', 'Overlock seams', 'Flatlock seams', 'Double needle hem'],
  Blazers: ['Single needle hem', 'Overlock seams', 'Flatlock seams', 'Double needle hem'],
  Blouses: ['Single needle hem', 'Overlock seams', 'Flatlock seams', 'Buttonhole stitching'],
  'Crop Tops': ['Single needle hem', 'Overlock seams', 'Flatlock seams'],
  Dresses: ['Single needle hem', 'Overlock seams', 'Flatlock seams', 'Zipper insertion'],
  Skirts: ['Single needle hem', 'Overlock seams', 'Flatlock seams', 'Double needle hem'],
  Rompers: ['Single needle hem', 'Overlock seams', 'Flatlock seams'],
  Onesies: ['Single needle hem', 'Overlock seams', 'Flatlock seams'],
  Bodysuits: ['Single needle hem', 'Overlock seams', 'Flatlock seams'],
  Sleepers: ['Single needle hem', 'Overlock seams', 'Flatlock seams'],
};
