export default {
  'T-Shirts': ['Branded neck tape', 'Woven label', 'Care label', 'Size label', 'Hang tag'],
  'Polo Shirts': [
    'Branded neck tape',
    'Woven label',
    'Care label',
    'Size label',
    'Hang tag',
    'Button placket',
  ],
  Hoodies: [
    'Branded neck tape',
    'Woven label',
    'Care label',
    'Size label',
    'Hang tag',
    'Drawstring',
  ],
  Sweatshirts: ['Branded neck tape', 'Woven label', 'Care label', 'Size label', 'Hang tag'],
  'Tank Tops': ['Branded neck tape', 'Woven label', 'Care label', 'Size label', 'Hang tag'],
  'Long Sleeve Tees': ['Branded neck tape', 'Woven label', 'Care label', 'Size label', 'Hang tag'],
  Shorts: ['Woven label', 'Care label', 'Size label', 'Hang tag', 'Waistband'],
  Pants: ['Woven label', 'Care label', 'Size label', 'Hang tag', 'Waistband'],
  Jeans: ['Woven label', 'Care label', 'Size label', 'Hang tag', 'Leather patch'],
  Jackets: ['Woven label', 'Care label', 'Size label', 'Hang tag', 'Zipper pull'],
  Blazers: ['Woven label', 'Care label', 'Size label', 'Hang tag', 'Lining'],
  Blouses: ['Woven label', 'Care label', 'Size label', 'Hang tag', 'Button placket'],
  'Crop Tops': ['Woven label', 'Care label', 'Size label', 'Hang tag'],
  Dresses: ['Woven label', 'Care label', 'Size label', 'Hang tag', 'Zipper'],
  Skirts: ['Woven label', 'Care label', 'Size label', 'Hang tag', 'Waistband'],
  Rompers: ['Woven label', 'Care label', 'Size label', 'Hang tag'],
  Onesies: ['Woven label', 'Care label', 'Size label', 'Hang tag'],
  Bodysuits: ['Woven label', 'Care label', 'Size label', 'Hang tag'],
  Sleepers: ['Woven label', 'Care label', 'Size label', 'Hang tag'],
};
